import {createRequire} from 'node:module';import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {PRESETS,COVERAGE} from '../src/engine/catalog.mjs';import {SPACE_PRESETS} from '../src/engine/spaces.mjs';import {VR_PRESETS} from '../src/engine/vr.mjs';
const require=createRequire(import.meta.url),sharp=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/sharp':'sharp');
await mkdir('previews/contact-sheets',{recursive:true});const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const banks=[{id:'regular',title:'Regular formations',presets:PRESETS,stages:4},{id:'spaces',title:'Polygon spaces',presets:SPACE_PRESETS,stages:3},{id:'video',title:'Spherical video studies',presets:VR_PRESETS,stages:3}];
const sprite=new Map(),metadata=new Map();
for(const bank of banks)for(let block=0;block<4;block++){
 const still=[],sequence=[];
 for(let frame=0;frame<bank.stages;frame++){
  const composites=[];
  for(let cell=0;cell<64;cell++){
   const p=bank.presets[block*64+cell],folder=bank.id==='regular'?'previews/presets':'previews/spatial-frames';
   const file=folder+'/'+p.id+'.webp';if(!metadata.has(file))metadata.set(file,await sharp(file).metadata());
   // WebP combines identical neighboring frames; recover each sampled stage from its duration.
   const delays=metadata.get(file).delay||[650],target=frame*delays.reduce((a,b)=>a+b,0)/bank.stages;let elapsed=0;
   const page=delays.findIndex(delay=>{elapsed+=delay;return target<elapsed;});
   const input=await sharp(file,{page:Math.max(0,page),pages:1}).resize(240,135,{kernel:'nearest'}).toBuffer();composites.push({input,left:cell%8*240,top:Math.floor(cell/8)*158});
   const label=Buffer.from(`<svg width="240" height="23" xmlns="http://www.w3.org/2000/svg"><rect width="240" height="23" fill="#10171b"/><text x="7" y="14" font-family="sans-serif" font-size="9" fill="#afbdc8">${esc((p.id+' · '+p.name).slice(0,55))}</text></svg>`);composites.push({input:label,left:cell%8*240,top:Math.floor(cell/8)*158+135});
   sprite.set(p.id,{file:bank.id+'-'+(block+1)+'.webp',position:`${cell%8/7*100}% ${Math.floor(cell/8)/7*100}%`});
  }
  const image=sharp({create:{width:1920,height:1264,channels:3,background:'#000'}}).composite(composites);
  if(frame===1)await image.clone().png().toFile('previews/contact-sheets/'+(bank.id==='regular'?'catalog':bank.id)+'-'+(block+1)+'.png');sequence.push(await image.raw().toBuffer());
 }
 if(bank.id!=='regular')await sharp(Buffer.concat(sequence),{raw:{width:1920,height:1264*bank.stages,channels:3,pageHeight:1264}}).webp({quality:78,loop:0,delay:Array(bank.stages).fill(650)}).toFile('previews/contact-sheets/'+bank.id+'-'+(block+1)+'.webp');
}
const cards=p=>{const s=sprite.get(p.id),visual=p.space||p.video?`<a href="contact-sheets/${s.file}" class="thumb" style="background-image:url('contact-sheets/${s.file}');background-position:${s.position}" aria-label="${esc(p.name)} rendered stages"></a>`:`<a href="presets/${p.id}.webp"><img src="presets/${p.id}.webp" loading="lazy" alt="${esc(p.description)}"></a>`;return `<article>${visual}<p class="tag">${p.id}</p><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><details><summary>Composition &amp; music</summary><p>${esc(p.distinction)}</p><p>${esc(p.audioBehavior)}</p></details></article>`;};
const sections=banks.map(bank=>`<section id="${bank.id}"><h2>${bank.title} · 256</h2><div class="grid">${bank.presets.map(cards).join('')}</div></section>`).join('');
await writeFile('previews/index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Video32 · Repertoire atlas</title><style>body{background:#080c0f;color:#d4dfe8;font:14px system-ui;margin:30px}main{max-width:1440px;margin:auto}h1{font-weight:350;font-size:42px;letter-spacing:-1px}h2{margin-top:50px;font-weight:450}p{color:#8e9fac;line-height:1.5}a{color:#50e8c4}nav{line-height:2.1}nav a{margin-right:15px}article{border:1px solid #ffffff19;border-radius:8px;overflow:hidden;padding:0 0 16px;background:#10171b}article p,article h3,article details{margin:12px 16px}article img{width:100%;display:block;image-rendering:pixelated}.thumb{display:block;aspect-ratio:240/158;background-size:800% 800%;image-rendering:pixelated}h3{font-weight:450;font-size:20px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.tag{font-size:10px;color:#50e8c4}details{font-size:11px}summary{cursor:pointer}footer{margin:40px 0}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){body{margin:15px}.grid{grid-template-columns:1fr}}</style></head><body><main><p>VIDEO32 / REPERTOIRE ATLAS</p><h1>768 glyph creations.</h1><p>Three banks. Every image comes from the actual renderer with simulated musical features. Regular previews sample four stages; spatial previews sample 0, 7 and 23 seconds. These are inspection sequences, not real-time performance measurements.</p><p>The video bank contains nine-frame studies from 256 distinct licensed 360° videos viewed through 180°, without reconstructed depth. Polygon tours use 32 source spaces. Source-derived previews retain their data licences; <a href="../space-credits.html">credits and interpretations</a> accompany the runnable extension.</p><nav>${banks.map(b=>`<a href="#${b.id}">${b.title}</a>`).join('')}</nav>${sections}<footer>Canonical bitmap glyphs and palette research © Shael Riley. OSM © OpenStreetMap contributors · ODbL; Kenney · CC0; Freedoom contributors · BSD; USGS terrain · public domain. Video studies: UGC360 Dataset · CC BY-SA 4.0. Per-source attribution and provenance accompany the source.</footer></main></body></html>`);
await writeFile('docs/preset-inventory.json',JSON.stringify({...COVERAGE,totalPresetCount:768,banks:banks.map(b=>({id:b.id,count:b.presets.length,ids:b.presets.map(p=>p.id)})),polygonSources:32,distinctVideoSources:256,videoSourceFrames:9},null,2));console.log({atlas:768,contactSheets:12,spatialAnimatedSheets:8});
