import {createRequire} from 'node:module';import {mkdir,writeFile,readFile} from 'node:fs/promises';import {PRESETS,COVERAGE} from '../src/engine/catalog.mjs';
const require=createRequire(import.meta.url),sharp=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/sharp':'sharp');
await mkdir('previews/contact-sheets',{recursive:true});
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
for(let block=0;block<4;block++){
 const composites=[];
 for(let row=0;row<8;row++)for(let col=0;col<8;col++){
  const p=PRESETS[block*64+row*8+col],input=await sharp('previews/presets/'+p.id+'.png').resize(240,135,{kernel:'nearest'}).toBuffer();composites.push({input,left:col*240,top:row*158});
  const svg=Buffer.from(`<svg width="240" height="23" xmlns="http://www.w3.org/2000/svg"><rect width="240" height="23" fill="#10171b"/><text x="7" y="14" font-family="sans-serif" font-size="9" fill="#afbdc8">${esc(p.id+' · '+p.name)}</text></svg>`);composites.push({input:svg,left:col*240,top:row*158+135});
 }
 await sharp({create:{width:1920,height:1264,channels:3,background:'#000'}}).composite(composites).png().toFile('previews/contact-sheets/catalog-'+(block+1)+'.png');
}
const cards=PRESETS.map(p=>`<article><a href="presets/${p.id}.webp"><img src="presets/${p.id}.webp" loading="lazy" alt="${esc(p.description)}"></a><p class="tag">${p.id} · ${p.camera}</p><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><details><summary>Composition &amp; music</summary><p>${esc(p.distinction)}</p><p>${esc(p.audioBehavior)}</p></details></article>`);
const grouped=[...new Set(PRESETS.map(p=>p.family))].map(f=>`<section id="${f}"><h2>${f}</h2><div class="grid">${cards.filter((_,i)=>PRESETS[i].family===f).join('')}</div></section>`).join('');
const nav=[...new Set(PRESETS.map(p=>p.family))].map(f=>`<a href="#${f}">${f}</a>`).join(' ');
await writeFile('previews/index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Video32 · Repertoire atlas</title><style>body{background:#080c0f;color:#d4dfe8;font:14px system-ui;margin:30px}main{max-width:1440px;margin:auto}h1{font-weight:350;font-size:42px;letter-spacing:-1px}h2{margin-top:50px;font-weight:450;text-transform:capitalize}p{color:#8e9fac;line-height:1.5}a{color:#50e8c4}nav{line-height:2.1}nav a{margin-right:15px}article{border:1px solid #ffffff19;border-radius:8px;overflow:hidden;padding:0 0 16px;background:#10171b}article p,article h3,article details{margin:12px 16px}article img{width:100%;display:block;image-rendering:pixelated}h3{font-weight:450;font-size:20px}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.tag{font-size:10px;color:#50e8c4}details{font-size:11px}summary{cursor:pointer}footer{margin:40px 0}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){body{margin:15px}.grid{grid-template-columns:1fr}}</style></head><body><main><p>VIDEO32 / REPERTOIRE ATLAS</p><h1>256 constructed worlds.</h1><p>32 generative families. Every image comes from the actual glyph renderer. These compact animations sample four development stages (0, 2.5, 8 and 23 seconds); they are inspection sequences, not real-time performance recordings. Test input is explicitly simulated.</p><p>The runnable extension includes a searchable library and live scenes. See the project README for installation.</p><nav>${nav}</nav>${grouped}<footer>Canonical bitmap glyphs and palette research © Shael Riley. Full provenance and measurements accompany the source.</footer></main></body></html>`);
await writeFile('docs/preset-inventory.json',JSON.stringify(COVERAGE,null,2));
const meta=await sharp('previews/presets/ribbon-01.webp',{animated:true}).metadata();console.log({atlas:256,contactSheets:4,sampledAnimationPages:meta.pages});
